### ISSUE TITLE
Fixing MessageBodyWriter issues

### ISSUE THREAD

**Issue by StephanSST** [baloise/corellia#46]
## Actual Behavior
Calling the Rest Endpoints leads to Resteasy Exceptions like this:
`
Caused by: org.jboss.resteasy.core.NoMessageBodyWriterFoundFailure: Could not find MessageBodyWriter for response object of type: ch.baloise.corellia.api.entities.ErrorResponse of media type: application/octet-stream at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:110) at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:187) ... 56 more
`

**Comment by MarkusTiede** [comment]
Background Information: https://download.oracle.com/otn-pub/jcp/jaxrs-2_0-edr2-spec/jaxrs-2_0-edr2-spec.pdf - Page 19 Chapter "3.6 Annotation Inheritance"

![image](https://user-images.githubusercontent.com/1764012/59421037-372d3600-8dce-11e9-8195-1f9a2ae00ff6.png)
